apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geekconsole-staging01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/devcraftftw/wordsmith-k8s.git'
    path: environments/staging01
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: geekconsole-staging01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true