---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress-stage.yaml
  - ingress-prod.yaml
  - default-headers-stage.yaml
  - default-headers-prod.yaml