---
apiVersion: v1
kind: Service
metadata:
  name: geekconsole
  labels:
    app: geekconsole
spec:
  ports:
    - port: 8080
      targetPort: 3000
      name: geekconsole
  selector:
    app: geekconsole
  type: NodePort