---
apiVersion: v1
kind: Service
metadata:
  name: geekconsole
  labels:
    app: geekconsole
spec:
  ports:
  - name: geekconsole-http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer